user/models.py

:card_file_box: FIX:interest fix

---

user/models.py

:ambulance: FIX:user model

---

user/admin.py
user/serializers.py
user/urls.py
user/views.py

user/admin.py 필드셋 추가, views, urls, serializers 추가

:sparkles: Feat: 회원탈퇴, 프로필 보기, 수정 추가 #1 #3

---

user/urls.py
user/views.py

:adhesive_bandage: Fix: 인증링크 로그인페이지로 연결 #1

---

nuriggun/settings.py
user/serializers.py

:adhesive_bandage: FIX : settings.py social login review #1 #2 

---

user/serializers.py

:adhesive_bandage:Fix: 하단에 배치된 import 상단으로 변경 #13

---

nuriggun/settings.py
user/serializers.py
user/urls.py
user/views.py

settings.py 화이트리스트 추가, user/serializers.py, urls.py, views.py 누락 추가

:zap: Fix: 회원가입, 비밀번호 재설정 기능 변경 #1

---

nuriggun/settings.py
user/serializers.py
user/views.py

+ 🩹 Fix: 포트번호 5000->5500으로 변경 등 자잘한 수정

✨ Feat: 회원가입 시리얼라이저 정규표현식 추가 #1 

---

article/serializers.py
user/serializers.py

article/serializers.py, user/serializers.py 수정

:bug: Fix: 글작성 400, profile_img 수정 #5 #3

---

article/serializers.py
user/serializers.py

article/serializers.py, user/serializers.py 수정

🐛 Fix: 글작성 400, profile_img 수정 #5 #3

---

article/models.py
article/serializers.py
article/urls.py
article/views.py
user/serializers.py

article models.py 자잘수정, user/serializers.py 비밀번호 재설정 정규식 추가

:sparkles: Feat: 메인페이지 정렬, 페이지네이션 #5

---

article/serializers.py

게시글 좋아요 수정 (시리얼 라이저 반응 카운트)

---

article/models.py
article/serializers.py
article/urls.py
article/views.py
nuriggun/settings.py
user/models.py
user/views.py

🐛 FIX : category fix 

---

article/views.py

⚡ Fix: article app) scrap status.HTTP updat #11

---

article/serializers.py
article/views.py
user/serializers.py
user/urls.py
user/views.py

user/urls,serializers,views. article/serializers,views수정

:sparkles: Feat: 메인-유저리스트 추가 #4

---

article/serializers.py

article_serializers.py) ArticleListSerializer : 게시글 반응 결과 추가

⚡ Feat: ArticleListSerializer) add reaction

---

article/serializers.py
article/views.py
user/views.py

user.views / article.views, serializers에서 작업

:sparkles: Feat: 오늘의 hot뉴스 추가, 기자구독 pagination추가 #74

---

article/serializers.py

🩹 add ArticleSerializer comments_count

---

article/serializers.py
user/serializers.py
user/views.py

article/serializers.py, user/serializers.py, views.py 수정

:zap: Fix: 서버배포 전 redirect주소 도메인으로 변경

---

article/serializers.py
user/serializers.py
user/views.py

article/serializers.py, user/serializers.py, views.py 수정

⚡ Fix: 서버배포 전 redirect주소 도메인으로 변경 

---

article/models.py
article/serializers.py
article/views.py

⚡ Feat: add article image_content #5

---

article/serializers.py

CommentSerializer : 유저 프로필 이미지 추가

🩹 Feat: CommentSerializer add user.profile_img #7

---

article/views.py
user/serializers.py
user/urls.py
user/views.py

user/serializers, urls, views.py 수정

:ambulance: Fix: 회원가입 시 이메일 인증링크 에러 수정 #2

---

README.md
article/views.py
user/serializers.py
user/urls.py
user/views.py

user/serializers, urls, views.py 수정

🚑 Fix: 회원가입 시 이메일 인증ㄹ이크 에러 수정 #2

---

user/admin.py
user/models.py
user/views.py

새 쪽지 알림을 위해 Message 모델에 is_read 추가

⚡ Feat: Message add is_read #13

---

article/serializers.py
user/admin.py
user/apps.py
user/models.py
user/serializers.py
user/signals.py
user/urls.py
user/views.py

✨ Feat: add email notification #16

---

article/models.py
article/serializers.py
article/views.py
user/serializers.py
user/views.py

article/models,serializers,views 수정. user/serializers, views 수정

:zap: Fix: 메인-유저리스트 탈퇴유저 안뜨도록 수정, user, article 코드 정리

---

templates/email_template.txt
templates/password_reset_template.html
user/serializers.py
user/views.py
weather/views.py

template폴더 변경, weather/views.py, user/serialisers, views.py 수정

:zap: Fix: 날씨 예외처리&retrycount추가, 이메일 템플릿 적용 #116

---

article/models.py
article/serializers.py
article/views.py
templates/email_template.txt
templates/password_reset_template.html
user/serializers.py
user/views.py
weather/views.py

template폴더 변경, weather/views.py, user/serialisers, views.py 수정

⚡ Fix: 날씨 예외처리&retrycount추가, 이메일 템플릿 적용 #116

---

user/views.py

:ambulance: Fix: user/views.py 5500포트 수정 #2

---

README.md

:memo: README 수정

---

weather/tests/test_api.py
weather/tests/test_views.py

:white_check_mark: Feat: weather app testcode 추가 #133

---

article/tests.py
user/tests.py
weather/views.py

article/tests.py user/tests.py에 HomeView관련 맨밑에 추가

:white_check_mark: Feat: HomeView(user,article) testcode 추가 #127 #128
